language: node_js
node_js:
- 8.11.1
env:
  matrix:
  - DEBUG="froq-http" DEBUG_COLORS=1
install:
- yarn install
- yarn run build
script:
- yarn run test:coverage
after_success: yarn run coverage
deploy:
  provider: npm
  email: renoth@wildoak.de
  api_key:
    secure: bxLFWs7K3Tt3S756unB2j7LkFCdhv68lDMkHzN9vMfYEIq3v8efpPpFCm1kkepn3SLQBPXDGpaL8nbK0jLI0KYViPUK0RsM1rNGpB3z6jmtdOeqrImpT2Mo/nbJ+Nca34dGe1lCHHoupaLjBBs538kc/5FsxetUMaioTBr+QK+13ZhK5MCU04uUi9YkcUC0ZVUGbk5i91uUcHd5U7WcSOdYoe884uSCRvd+8rwptONnPc+JgyrGWwm9rZgf0nOv/iUKsiaMcTwuGgm3uomX2pOAD7aG5TIa1Sh1B3KMzlC49Ab6b8kZcNbRcznVG3LEcoR2Cu4Qnh40EMwY95Wz15DsR89AgaTnTFWMA1yNv55s4lRlYtHth+1ar8ewd+tq+s5xxeEGxE0m7eCa8FYy5I45XfJ23fiob/3LPGLa9ZH+ThaPvhYErGMhMO4xToAqlo7eGd5OliEKjjgdkb5gIAYQrjrVmJfOxxJskJtEj9kauGkLdDi2XCbOcJtJkqUOO2UI6McYxrFKnxVQ0KQmit+d27PBtrKJkvBMvZ1ueTtgfhUOZHe0GRTJIqjRm77//M6GyO8b3NG54BRXThZxOWY5YS5KianfM0A1Zn+EJg6vzDUZ+Y0v5AdZfNqeyWJ3IIj+c7mxFg+FtqIxbC8GzISw7xLAWj95+4ksjn8JVe8o=
  on:
    tags: true
